"""Generate vocab/index.html so srd: predicate IRIs dereference."""

from __future__ import annotations

import argparse
import html
from pathlib import Path

from srdlib import BASE, COLLECTION_TYPES, load_json


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    args = parser.parse_args()
    root = Path(args.root).resolve()

    context = load_json(root / "systems/context.jsonld")["@context"]
    terms = []
    for term, definition in sorted(context.items()):
        if term.startswith("@") or term in ("srd", "schema", "dcterms"):
            continue
        iri = definition["@id"] if isinstance(definition, dict) else definition
        if not str(iri).startswith("srd:"):
            continue
        kind = "relationship" if isinstance(definition, dict) and definition.get("@type") == "@id" else "literal"
        terms.append((str(iri).split(":", 1)[1], term, kind))
    classes = sorted(set(COLLECTION_TYPES.values()) | {"SRDSystemData"})

    rows = "\n".join(
        f'<tr id="{html.escape(anchor)}"><td><code>srd:{html.escape(anchor)}</code></td>'
        f"<td>{html.escape(term)}</td><td>{kind}</td></tr>"
        for anchor, term, kind in terms
    )
    class_rows = "\n".join(
        f'<tr id="{html.escape(name)}"><td><code>srd:{html.escape(name)}</code></td>'
        f"<td>JSON-LD class</td><td>class</td></tr>"
        for name in classes
    )
    page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>SRD 5.2.1 System JSON Vocabulary</title>
<style>
body {{ font: 15px/1.6 system-ui, sans-serif; max-width: 52rem; margin: 2rem auto; padding: 0 1rem; }}
table {{ border-collapse: collapse; width: 100%; }}
td, th {{ border: 1px solid #ccc; padding: .35rem .6rem; text-align: left; }}
code {{ background: #f2f2f2; padding: .05rem .3rem; border-radius: 4px; }}
</style>
</head>
<body>
<h1>SRD 5.2.1 System JSON Vocabulary</h1>
<p>Terms in the <code>{html.escape(BASE)}vocab/</code> namespace, as defined by
<a href="../systems/context.jsonld">systems/context.jsonld</a>. Generated by
<code>scripts/build_vocab.py</code>; do not edit by hand.</p>
<h2>Classes</h2>
<table><tr><th>IRI</th><th>JSON term</th><th>Kind</th></tr>
{class_rows}
</table>
<h2>Properties</h2>
<table><tr><th>IRI</th><th>JSON term</th><th>Kind</th></tr>
{rows}
</table>
</body>
</html>
"""
    out = root / "vocab/index.html"
    out.parent.mkdir(exist_ok=True)
    out.write_text(page, encoding="utf-8")
    print(f"vocab: {len(terms)} properties, {len(classes)} classes")


if __name__ == "__main__":
    main()
